language: EN
strict: true
strictness_threshold: high
output:
  file_path: results-sast.csv
  format: CSV
sast:
  include:
    - .
  exclude: # Optional: paths to exclude from scanning
    - node_modules
    - vendor