name: SAST
on:
  push:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for differential scanning

      - uses: fluidattacks/sast-action@1.3.0 # Use latest released version
        id: scan
        with:
          scan_config_path: .github/sast-config.yaml
          scanner_mode: full

      - name: Upload CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-sast
          path: results-sast.csv
          if-no-files-found: ignore

      - name: Fail on vulnerabilities
        if: steps.scan.outputs.vulnerabilities_found == 'true'
        run: exit 1