name: SCA
on:
  push:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: fluidattacks/sca-action@1.2.0
        id: scan
        with:
          scan_config_path: .github/sca-config.yaml

      - name: Upload CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-sca
          path: results-sca.csv
          if-no-files-found: ignore

      - name: Fail on vulnerabilities
        if: steps.scan.outputs.vulnerabilities_found == 'true'
        run: exit 1