name: SCA
on:
  push:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: fluidattacks/sca-action@1.2.0
        id: scan
        with:
          scan_config_path: .github/sca-config.yaml